apiVersion: v1
kind: Secret
metadata:
  name: driftguard-secrets
  namespace: driftguard
type: Opaque
data:
  # Base64 encoded values
  # github-token: "<base64-encoded-token>"
  # aws-access-key-id: "<base64-encoded-access-key>"
  # aws-secret-access-key: "<base64-encoded-secret-key>"