apiVersion: v1
kind: Secret
metadata:
  name: {{ include "driftguard.fullname" . }}-secrets
  labels:
    {{- include "driftguard.labels" . | nindent 4 }}
type: Opaque
data:
  github-token: {{ .Values.config.github.token | b64enc | quote }}